name: beer_like
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  sqflite: 2.3.1
  path_provider: 2.1.2
  http: 1.2.0
  intl: 0.19.0
  image_picker: 1.0.7
  firebase_core: 2.25.4
  firebase_auth: 4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/logo_splash.png
   - assets/background_splash.png
   - assets/images/